Controllers/RezultatiController.cs
using KvizZnanja.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KvizZnanja.Controllers
{
    public class RezultatiController : Controller
    {
        KvizZnanjaEntities db = new KvizZnanjaEntities();

        // metoda koja dohvaća podatke iz baze o svim rezultatima odigranih kvizova
        private List<KvizRezultatVM> Get()
        {
            List<KvizRezultatVM> rez = new List<KvizRezultatVM>();
            List<KvizRezultat> kvizRezultat = db.KvizRezultat.ToList();
            foreach (var kr in kvizRezultat)
            {
                KvizRezultatVM o = new KvizRezultatVM();
                o.KvizRezultat = kr;
                o.User = db.Users.Where(u => u.ID == kr.UserID).FirstOrDefault();
                List<KvizRezultatOdgovor> odgovori = db.KvizRezultatOdgovor.Where(odg => odg.KvizRezultatID == kr.ID).ToList();
                foreach (var odg in odgovori)
                {
                    o.Odgovori.Add(new KvizRezultatOdgovorVM()
                    {
                        ID = odg.ID,
                        KvizRezultatID = odg.KvizRezultatID.Value,
                        Pitanje = db.Pitanjes.Where(p => p.ID == odg.PitanjeID).FirstOrDefault(),
                        Odgovor = db.Odgovors.Where(odgovor => odgovor.ID == odg.UserOdgovorID).FirstOrDefault(),
                        TocanOdgovor = db.Odgovors.Where(odgovor => odgovor.ID == odg.TocanOdgovorID).FirstOrDefault()
                    });
                }
                rez.Add(o);
            }
            return rez;
        }

        // metoda koja dohvaća podatke iz baze o željenom rezultatu odigranog kviza
        private KvizRezultatVM Get(long ID)
        {
            KvizRezultat kvizRezultat = db.KvizRezultat.Where(kr => kr.ID == ID).FirstOrDefault();
            KvizRezultatVM rez = new KvizRezultatVM();
            rez.KvizRezultat = kvizRezultat;
            rez.User = db.Users.Where(u => u.ID == kvizRezultat.UserID).FirstOrDefault();
            List<KvizRezultatOdgovor> odgovori = db.KvizRezultatOdgovor.Where(odg => odg.KvizRezultatID == rez.KvizRezultat.ID).ToList();
            foreach (var odg in odgovori)
            {
                rez.Odgovori.Add(new KvizRezultatOdgovorVM()
                {
                    ID = odg.ID,
                    KvizRezultatID = odg.KvizRezultatID.Value,
                    Pitanje = db.Pitanjes.Where(p => p.ID == odg.PitanjeID).FirstOrDefault(),
                    Odgovor = db.Odgovors.Where(odgovor => odgovor.ID == odg.UserOdgovorID).FirstOrDefault(),
                    TocanOdgovor = db.Odgovors.Where(odgovor => odgovor.ID == odg.TocanOdgovorID).FirstOrDefault()
                });
            }
            return rez;
        }

        // metoda ucitava pregled svih rezultata
        public ActionResult Index()
        {
            ViewBag.rezultati = this.Get();
            return View();
        }

        // metoda ucitava detaljan pregled rezultata
        public ActionResult Details(int ID)
        {
            ViewBag.rezultat = this.Get(ID);
            
            return View();
        }

        // metoda brise iz baze podatke o rezultatima odigranog kviza
        public ActionResult Delete(long ID) {
            if(ID > 0)
            {
                List<KvizRezultatOdgovor> toRemove = db.KvizRezultatOdgovor.Where(kro => kro.KvizRezultatID == ID).ToList();
                KvizRezultat rez = db.KvizRezultat.Where(kr => kr.ID == ID).FirstOrDefault();

                db.KvizRezultatOdgovor.RemoveRange(toRemove);
                db.KvizRezultat.Remove(rez);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Rezultati/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Detalji: <b class="text-primary">@ViewBag.rezultat.KvizRezultat.NazivKviza</b></h2>
<h2>Korisnik: <b class="text-primary">@ViewBag.rezultat.User.Ime  @ViewBag.rezultat.User.Prezime</b></h2>
<hr />

@if (ViewBag.rezultat != null)
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="text-center">Pitanje #</th>
                <th>Pitanje</th>
                <th>Korisnikov odgovor</th>
                <th>Točan odgovor</th>
            </tr>
        </thead>

        <tbody>
            @{ int i = 1; }
            @foreach(var r in ViewBag.rezultat.Odgovori)
            {
                <tr class="@if (Convert.ToBoolean(r.Odgovor.IsTocanOdgovor)) { @Html.Raw("table-row-success"); } else { @Html.Raw("table-row-danger");  } ">
                    <td class="text-center">@i.</td>
                    <td>@r.Pitanje.Value</td>
                    <td>@r.Odgovor.Value</td>
                    <td>@r.TocanOdgovor.Value</td>
                </tr>
                i++;
            }
        </tbody>
    </table>
}
else
{
    <h3 style="color:blue;">Nema detalja!</h3>
}

Views/Rezultati/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Pregled rezultata</h2>
<hr />



@if (ViewBag.rezultati.Count > 0)
{
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th class="text-center">#</th>
                <th>Naziv kviza</th>
                <th>Ime i prezime korisnika</th>
                <th>Datum i vrijeme</th>
                <th>Točnih</th>
                <th>Netočnih</th>
                <th>Postotak</th>
                <th>Vrijeme trajanja</th>
                <th></th>
                @if (KvizZnanja.Models.Authentication.IsAdmin())
                {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @{ int i = 1;}
            @foreach (var r in ViewBag.rezultati)
            {
                <tr>
                    <td class="text-center" style="width:5%">@i.</td>
                    <td>@r.KvizRezultat.NazivKviza</td>
                    <td>@r.User.Ime  @r.User.Prezime</td>
                    <td>@r.KvizRezultat.DatumIVrijeme.ToString("dd-MM-yyyy HH:mm:ss")</td>
                    <td>@r.KvizRezultat.Tocnih</td>
                    <td>@r.KvizRezultat.Netocnih</td>
                    <td>@r.KvizRezultat.Postotak %</td>
                    <td>@r.KvizRezultat.VrijemeTrajanja s</td>
                    <td class="text-center" style="width:13%">
                        <button type="button" class="btn btn-info" onclick="@("window.location.href='" + @Url.Action("Details", "Rezultati", new { ID = r.KvizRezultat.ID }) + "'");"><i class="glyphicon glyphicon-info-sign"></i>&nbsp;&nbsp;Detalji</button>
                    </td>
                    @if (KvizZnanja.Models.Authentication.IsAdmin())
                    {
                        <td class="text-center" style="width:13%">
                            <button type="button" class="btn btn-danger" onclick="@("window.location.href='" + @Url.Action("Delete", "Rezultati", new { ID = r.KvizRezultat.ID }) + "'");"><i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;Briši</button>
                        </td>
                    }
                </tr>
                i++;
            }
        </tbody>
    </table>
}
else
{
    <h3 style="color:blue;">Nema unesenih rezultata u bazi!</h3>
}